2022-01-29 11:05:41,703  kundev : hsuser : 151452 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:05:41,716  kundev : hsuser : 151452 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-110541.txt
2022-01-29 11:05:41,737  kundev : hsuser : 151452 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:06:12,595  kundev : hsuser : 152002 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:06:12,645  kundev : hsuser : 152002 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-110612.txt
2022-01-29 11:06:12,683  kundev : hsuser : 152002 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:07:52,472  kundev : hsuser : 153460 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:07:52,494  kundev : hsuser : 153460 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-110752.txt
2022-01-29 11:07:52,508  kundev : hsuser : 153460 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:16:34,608  kundev : hsuser : 153844 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:16:34,626  kundev : hsuser : 153844 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-111634.txt
2022-01-29 11:16:34,639  kundev : hsuser : 153844 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:17:01,289  kundev : hsuser : 153874 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:17:01,304  kundev : hsuser : 153874 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-111701.txt
2022-01-29 11:17:01,318  kundev : hsuser : 153874 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:17:10,355  kundev : hsuser : 153906 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:17:10,371  kundev : hsuser : 153906 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-111710.txt
2022-01-29 11:17:10,384  kundev : hsuser : 153906 : gui_logger:81 [ERROR] Uncaught exception: AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
Traceback (most recent call last):
  File "/oys/xtal/dials/dials-v1-14-13/build/../modules/yamtbx/command_line/kamo.py", line 17, in <module>
    auto_data_proc_gui.run_from_args(sys.argv[1:])
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/dataproc/auto/command_line/auto_data_proc_gui.py", line 1988, in run_from_args
    batchjobs = batchjob.SGE(pe_name=config.params.batch.sge_pe_name)
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 149, in __init__
    self.engine = detect_engine()
  File "/oys/xtal/dials/dials-v1-14-13/modules/yamtbx/util/batchjob.py", line 331, in detect_engine
    if e.returncode == 2:
AttributeError: 'exceptions.OSError' object has no attribute 'returncode'
2022-01-29 11:17:42,648  kundev : hsuser : 153956 : auto_data_proc_gui:1972 [INFO] Starting GUI in /data01/SGJ/220128-BL19XU/Scripts/_kamoproc
2022-01-29 11:17:42,663  kundev : hsuser : 153956 : auto_data_proc_gui:1981 [INFO] GUI parameters were saved as /data01/SGJ/220128-BL19XU/Scripts/_kamoproc/gui_params_220129-111742.txt
2022-01-29 11:17:42,663  kundev : hsuser : 153956 : auto_data_proc_gui:1996 [INFO] Automatically adjusting batch.sh_max_jobs based on available CPU number (8)
2022-01-29 11:17:42,664  kundev : hsuser : 153956 : auto_data_proc_gui:2014 [INFO] bl=other and dataset_paths_txt not specified. changing a parameter logwatch_target= to local.
2022-01-29 11:17:42,957  kundev : hsuser : 153956 : auto_data_proc_gui:914 [INFO] WatchLogThread already stopped.
2022-01-29 11:17:42,957  kundev : hsuser : 153956 : auto_data_proc_gui:920 [INFO] WatchLogThread loop STARTED
2022-01-29 11:17:50,220  kundev : hsuser : 153956 : auto_data_proc_gui:2061 [INFO] Normal exit.
